Tensorflow Object detection Using Efficientdet_d7_coco_tpu-32

In [2]:
#import neccessary libraries

import tensorflow as tf 
import cv2 as cv 
import numpy as np

In [3]:
#load tfod model
model_path = "efficientdet_d7_coco17_tpu-32/saved_model"
model = tf.keras.models.load_model(model_path)

c:\Users\XPRESS\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\layers\core\lambda_layer.py:297: UserWarning: google3.third_party.tensorflow.python.ops.nn_impl is not loaded, but a Lambda layer uses it. It may cause errors.
  function = cls._parse_function_from_config(config, custom_objects,
c:\Users\XPRESS\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\layers\core\lambda_layer.py:297: UserWarning: google3.third_party.tensorflow_models.object_detection.utils.bifpn_utils is not loaded, but a Lambda layer uses it. It may cause errors.
  function = cls._parse_function_from_config(config, custom_objects,


In [34]:
#read the labels of the detection 

with open('coco.names','r') as f:
    names = f.read().splitlines()

In [47]:
img =cv.imread(r"crosswalk-featured.jpg")
tensorimg = cv.cvtColor(img,cv.COLOR_BGR2RGB)  #convert BGR image to RGB image
tensorimg = tf.convert_to_tensor(tensorimg.copy(),dtype=tf.uint8) #convert image to tensorflw tensor
tensorimg = tensorimg[tf.newaxis,...] #expand dimensions 

detection = model(tensorimg)
detection_boxes = detection["detection_boxes"][0].numpy()
detection_classes = detection["detection_classes"][0].numpy().astype(np.int32)
detection_scores = detection["detection_scores"][0].numpy()



random_color = np.random.uniform(low=0,high=255,size=(80,3))

bboxIdx = tf.image.non_max_suppression(detection_boxes,detection_scores,max_output_size=50,iou_threshold=0.5,score_threshold=0.5)


#function to create bounding box

def create_bbox(image):
    imH,imW,imC = image.shape
    for i in bboxIdx:
        bbox = tuple(detection_boxes[i].tolist())
        classname = detection_classes[i]
        classname = names[classname-1]
        ymin,xmin,ymax,xmax =bbox
        ymin,xmin,ymax,xmax = (ymin*imH,xmin*imW,ymax*imH,xmax*imW)
        ymin = int(ymin)
        xmin = int(xmin)
        ymax = int(ymax)
        xmax = int(xmax)
        
        # print(ymin,ymax,xmin,xmax)
        center1 = int((xmin+xmax)/2)
        center2 = int((ymin+ymax)/2)
        center3 = np.random.randint(xmax/2,xmax)
        center4 = np.random.randint(ymin,ymax)
        center5 = np.random.randint(ymin,ymax)
    
        print(center3,center4)
        if (center3-center4) < 200:
            center3 += 100
            center4 += 100
        else:
            pass
        
        color =random_color[i]
        print(color)
    
        cv.rectangle(image,(xmin,ymin),(xmax,ymax),(color),1)
        cv.line(image,(xmin,ymin),(xmin+20,ymin),(color),3)
        cv.line(image,(xmin,ymin),(xmin,ymin+20),(color),3)
        cv.line(image,(xmax-20,ymin),(xmax,ymin),(color),3)
        cv.line(image,(xmax,ymin),(xmax,ymin+20),(color),3)
        cv.line(image,(xmax,ymax),(xmax-20,ymax),(color),3)
        cv.line(image,(xmax,ymax-20),(xmax,ymax),(color),3)
        cv.line(image,(xmin+20,ymax),(xmin,ymax),(color),3)
        cv.line(image,(xmin,ymax-20),(xmin,ymax),(color),3)
        cv.putText(image,(classname.upper()),(xmin,ymin-5),cv.FONT_HERSHEY_PLAIN,1.0,(color),2)


    return image





image = create_bbox(img)
cv.imshow("img",image)


cv.waitKey(0)
cv.destroyAllWindows()


770
##################
438 209
[ 89.91189339 112.97890126 208.51426595]
##################
352 269
[ 36.14658754 216.86299912 151.74856852]
##################
675 355
[248.31401365 234.17590993   2.15155648]
##################
620 235
[171.17164162  51.41402877 110.12254285]
##################
134 278
[221.22355015 132.97385959  74.90448937]
##################
326 222
[ 94.5925911  237.48703073  25.67982466]
##################
639 222
[173.29640045 161.47596151 105.83043005]
##################
391 260
[210.10655285  84.45207118  54.48117106]
##################
121 202
[103.27853854  99.93893642 177.59429877]
##################
370 200
[175.90890994 214.14906414   2.47150883]
##################
175 332
[ 77.75197892  64.46193644 116.08914772]
##################
312 311
[ 83.26285854 218.40723807 144.83097986]
##################
85 200
[163.34508033  64.58492344  18.49001676]
##################
227 191
[116.82911942 107.94619275  21.42163969]
##################
581 223
[111.13234356 224.